#!/usr/bin/env bash
# Script that creates a backup for database

# assign first arg to variable "password"
password=$1

# dump all MySQL databases
mysqldump --user=root --password=$password --all-databases > backup.sql

# Assign the current date to variable "date"
date=$(date +"%d-%m-%Y")

# compress the dump file to tar.gz archive
tar -zcvf $date.tar.gz backup.sql
