#!/usr/bin/env bash
# Script that configures ubuntu server by changing the below requirements:
# locahosts resolves to "127.0.0.2"
# facebook.com resolves to "8.8.8.8"
# This scenario is running on Docker

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm -f ~/hosts.new